[package]
name = "lunka"
description = "`#![no_std]` bindings to Lua 5.4"
authors = [ "[aka]bomb" ]
license = "MIT"
version = "0.4.0"
edition = "2021"
repository = "https://github.com/b0mbie/lunka"

[[example]]
name = "interpreter"

[features]
# Use definitions for 32 bits max.
# This is analogous to the `LUA_32BITS` define, and should be set appropriately
# depending on the compiled Lua settings.
# It's usually set to `0`, so this is disabled by default.
use-32-bits = []

# Include and use stuff from `lauxlib.h`.
auxlib = []

# Include and use definitions for importing the standard libraries (in `lualib.h`).
stdlibs = []

default = [ "auxlib", "stdlibs" ]

[dependencies.allocator-api2]
version = "0.2.16"
default-features = false
features = [ "alloc" ]
