[package]
name = "lunka"
description = "`#![no_std]` bindings to Lua 5.4"
authors = [ "[aka]bomb" ]
license = "MIT"
version = "0.5.3"
edition = "2021"
repository = "https://github.com/b0mbie/lunka"

[[example]]
name = "interpreter"

[features]
# Use definitions for 32 bits max.
# This is analogous to the `LUA_32BITS` define, and should be set appropriately
# depending on the compiled Lua settings.
# It's usually set to `0`, so this is disabled by default.
use-32-bits = []

# Include and use stuff from `lauxlib.h`.
auxlib = []

# Include and use definitions for importing the standard libraries (in `lualib.h`).
stdlibs = []

# Link `lua54` statically.
# This may be useful for applications, since Lua will become embedded in the
# executable.
link-static = []

# Don't include `link` attributes in the crate source code.
# You may enable this if, for example, you have your own `build.rs` script that
# links Lua in a different way.
link-manually = []

default = [ "auxlib", "stdlibs" ]

[dependencies.allocator-api2]
version = "0.2.16"
default-features = false
features = [ "alloc" ]
